seneca = User.by_login("seneca") || Factory(:user, :login => "seneca")
lucilius = User.by_login("lucilius") || Factory(:user, :login => "lucilius")
marcus = User.by_login("marcus") || Factory(:user, :login => "marcus_aurelius")
cicero = User.by_login("cicero") || Factory(:user, :login => "cicero")
homer = User.by_login("homer") || Factory(:user, :login => "homer")
machiavelli = User.by_login("machiavelli") || Factory(:user, :login => "machiavelli")
cesare = User.by_login("cesare") || Factory(:user, :login => "cesare")

Factory(:lending, :category => "book", :title => "Letters from a Stoic", :from => seneca.id, :to => lucilius.id, :time => 30)
Factory(:lending, :category => "book", :title => "The Prince", :from => machiavelli.id, :to => cesare.id, :time => 30)
Factory(:lending, :category => "book", :title => "Odyssey", :from => homer.id, :to => cicero.id, :time => 7)
Factory(:lending, :category => "book", :title => "Iliad", :from => homer.id, :to => machiavelli.id, :time => 7)
Factory(:lending, :category => "book", :title => "Meditations", :from => marcus.id, :to => seneca.id, :time => 300)
Factory(:lending, :category => "letter", :title => "Pro Sulla", :from => cicero.id, :to => marcus.id, :time => 100)
Factory(:lending, :category => "cd", :title => "Arctic Monkeys - Your favorite worst nightmare", :from => marcus.id, :to => cesare.id, :time => 2)